import './globals.css';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import { getLang } from '../i18n/i18n_functions';

const WorkSans = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Joaquín Veirana',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={getLang()}>
      <body
        className={`${WorkSans.className} scrollbar-thin scrollbar-thumb-rounded scrollbar-thumb-light-secondary-color-200 scrollbar-track-dark-300`}
      >
        {children}
      </body>
    </html>
  );
}
